### ISSUE TITLE
Docker files created by dartfn doesn't copy runtime files, causing launch to fail

### ISSUE THREAD

**Issue by weenzeel** [GoogleCloudPlatform/functions-framework-dart#282] opened 2021-09-13 06:31 UTC
Steps to reproduce ...

Run `dartfn generate helloworld` in a new folder.

As instructed by the README file in the generated test-project. Run commands ...

```
docker build -t hello .
docker run -it -p 8080:8080 --name app hello
```

This fails with the message: _standard_init_linux.go:228: exec user process caused: no such file or directory_

To fix the error, one needs to manually add the following line to the generated docker file:

`COPY --from=0 /runtime/ /`

Also, on a side note, the docker files created by dartfn differs in different ways from the docker files being present in the project example files directory. Could these versions of docker files be more aligned/kept in sync?

All the best!

**Comment by kevmoo** [comment] 2021-09-13 17:31
Duplicate of #268

**Closed by kevmoo** 2021-09-13 17:31 UTC

**Comment by kevmoo** [comment] 2021-09-13 20:51
This is now fixed – thanks to @subfuzion – update `dartfn` and you should be good to go!

**Comment by weenzeel** [comment] 2021-09-13 21:07
Awesome! Thanks for being so responsive. Dart on the server has great potential.
