### ISSUE TITLE
Add Firebase SDK

### ISSUE THREAD

**Issue by buttonsrtoys** [GoogleCloudPlatform/functions-framework-dart#265] opened 2021-07-31 10:47 UTC
**Feature**
Add Firebase SDK to Functions Framework so native Dart in GCP can call Firebase/Firestore.

**Use Case**
Flutter developers using Firestore would be much more productive if they used Dart in their backend with calls to a Firestore API. Stack would be Dart/Flutter on the front end and Dart/Firestore on the backend. 

When debugging backend code, the ability to add breakpoints and step through Dart code while observing the Firestore emulator would be a game changer.

**Prior Online Discussions**
[Reddit 11/2020](https://www.google.com/url?sa=t&source=web&rct=j&url=https://amp.reddit.com/r/dartlang/comments/jzict9/functions_framework_for_dart_is_heading_your_way/&ved=2ahUKEwj8wd_sjY3yAhXBHc0KHajDCjYQFjAAegQIAxAC&usg=AOvVaw2NIACnZHmwPNzNip_A2TkZ)
[Reddit 7/2021](https://www.google.com/url?sa=t&source=web&rct=j&url=https://amp.reddit.com/r/FlutterDev/comments/o5tim5/what_the_status_on_using_native_dart_with/&ved=2ahUKEwiDrK_gkI3yAhVGB50JHfsyD5IQFjADegQIKhAC&usg=AOvVaw0qZhzucW6h5qvTKTWVrNVw)

**Comment by blaueeiner** [comment] 2021-09-02 13:19
Just add [Googleapis](https://pub.dev/packages/googleapis) to your project dependencies to communicate to any Google API like Firestore. No need for the Dart Functions Framework to depend on it.

**Comment by Patrick386** [comment] 2021-11-17 13:04
When will this be available?
A game changer must be introduced urgently!

**Comment by blaueeiner** [comment] 2021-11-17 14:36
@Patrick386 It makes no sense for the Functions Framework to be dependent on any Firebase specific SDK. You project should depend on something like a Firebase SKD instead.

**Comment by Patrick386** [comment] 2021-11-18 08:59
> @Patrick386 It makes no sense for the Functions Framework to be dependent on any Firebase specific SDK. You project should depend on something like a Firebase SKD instead.

I agree with you. I can't wait to use this function. Do you have any update on when to supported?

**Comment by kevmoo** [comment] 2021-12-20 23:17
Duplicate of https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/162 – but I agree!

**Closed by kevmoo** 2021-12-20 23:17 UTC
